# we'll change this to only suit data we actually need, right now works for all samples
OCR_PATTERNS = {
    "White blood cells": r"(?:White blood cell|WBC).*?\s+([\d,]+\.?\d*)",
    "Hemoglobin": r"(?:H(?:a)?emoglobin|HGB).*?\s+([\d,]+\.?\d*)",
    "Platelets": r"(?:Platelet|PLT).*?\s+([\d,]+\.?\d*)",
    "Red blood cells": r"(?:Red blood cell|RBC).*?\s+([\d,]+\.?\d*)",
    "Hematocrit": r"(?:Hematocrit|HCT).*?\s+([\d,]+\.?\d*)",
    "PCV": r"(?:Packed Cell Volume|PCV).*?\s+([\d,]+\.?\d*)",
    "MCV": r"MCV.*?\s+([\d,]+\.?\d*)",
    "MCH": r"MCH.*?\s+([\d,]+\.?\d*)",
    "MCHC": r"MCHC.*?\s+([\d,]+\.?\d*)",
    "RDW": r"RDW.*?\s+([\d,]+\.?\d*)",
    "LDL": r"LDL Chol.*?\s+([\d,]+\.?\d*)",
    "Triglycerides": r"Triglycerides.*?\s+([\d,]+\.?\d*)",
    "HDL": r"HDL Chol.*?\s+([\d,]+\.?\d*)",
    "Total Cholesterol": r"Total Chol.*?\s+([\d,]+\.?\d*)",
    "Glucose": r"(?:Glucose|Glicaemia).*?\s+([\d,]+\.?\d*)",
    "BUN": r"BUN.*?\s+([\d,]+\.?\d*)",
    "Creatinine": r"Creatinine.*?\s+([\d,]+\.?\d*)",
    "Sodium": r"Sodium.*?\s+([\d,]+\.?\d*)",
    "Potassium": r"Potassium.*?\s+([\d,]+\.?\d*)",
    "Chloride": r"Chloride.*?\s+([\d,]+\.?\d*)",
    "Calcium": r"Calcium.*?\s+([\d,]+\.?\d*)",
    "Protein, Total": r"Protein, Total.*?\s+([\d,]+\.?\d*)",
    "Albumin": r"Albumin.*?\s+([\d,]+\.?\d*)",
}